config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root "sessions#new"
    resources :kids
    resources :sessions, only: [:new, :create, :destroy]
    resources :foods
    resources :users
    
    get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kid.rb
class Kid < ApplicationRecord
    has_many :sayings
   
    def self.find_or_create_from_auth_hash(auth_hash)
      user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
      user.update(
        name: auth_hash.info.nickname,
        profile_image: auth_hash.info.image,
        token: auth_hash.credentials.token,
        secret: auth_hash.credentials.secret
      )
      user
    end
end

app/models/saying.rb
class Saying < ApplicationRecord
    belonhgs_to :kid
   
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password    
    validates :email, :presence => true, :uniqueness => true
  
    has_many :foods
    has_many :items, through: :foods
    
    def self.find_or_create_from_auth_hash(auth_hash)
      user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
      user.update(
        name: auth_hash.info.nickname,
        profile_image: auth_hash.info.image,
        token: auth_hash.credentials.token,
        secret: auth_hash.credentials.secret
      )
      user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController

  def index
  end
    
  def show
    @kid = Kid.find(params[:id])
  end


  def new
    @kid = Kid.new
#    @kid.sayings.build
  end

   def edit
   @kid = Kid.find(params[:id])
 end
  
  def create
    @kid = Kid.new(kid_params)
    
    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully added.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kidd.errors, status: :unprocessable_entity }
      end
    end
end
  
  def update
    @kid = Kid.find(params[:id])
    @kid.update(kid_params)
    redirect_to kid_path(@kid)
  end

  def destroy
     Kid.find(params[:id]).destroy
     redirect_to kids_url
  end
  

  private

    def set_kid
       @kid = Kid.find(params[:id])
    end
    
   def kid_params
          params.require(:kid).permit( :name, :saying)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
   
   def create
      user = User.find_by_email(params[:email])

     if user && user.authenticate(params[:password])
        session[:user_id] = user.id
       redirect_to "/users/index/", notice: "Logged in!"
     else
       flash.now[:alert] = "Email or password is invalid"
       render "/users/show/"
     end
   end
   
   
   def createauth
     @user = User.find_or_create_from_auth_hash(auth_hash)
     urrent_user = @user
     redirect_to "/users/index/", notice: "Logged in!"
   end
       
       
   
   def destroy
      if current_user
        session.delete(:user_id)
        redirect_to '/'
#        flash[:success] = "Sucessfully logged out!"
      else
         session.delete(:user_id)
         redirect_to '/', notice: "Logged out!"
      end
   end
   
   protected

   def auth_hash
     request.env['omniauth.auth']
   end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
      @user = User.new
  end
  
  def create
     @user = User.new(user_params)
     if @user.save
       flash[:notice] = "Account created successfully!"
       redirect_to '/users/show/'
     else
       flash.now.alert = "Please try again."
       render '/users/new/'
     end
   end
  
  def update
    end
  

private
   
   def user_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kids/_form.html.erb
<%= form_for (@kid) do |f| %>

<%= f.label :name %> <br>
<%= f.text_field :name %><br>

<%= f.label :saying %><br>
<%= f.text_field :saying %><br>

  <div class="actions">
  <br>
  <%= f.submit %>
  
  </div>
  
<% end %>

app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form', kid: @kid %>

<%= link_to 'Show', @kid %>
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<h1>Kid</h1>

<table>
<thead>
  <tr>
    <th></th>
  </tr>
</thead>

  <tbody>
  
      <% @kids.each do |kid| %>
      <tr>
          <td> <h2> <%= kid.name%></td> </h2>
          <td><h1>}</h1><td>
          <tr></tr>
          <td> <h4> <%= link_to 'Show', kid %></td> </h4>
          <tr></tr>
          <td><h4><%= link_to 'Edit', edit_kid_path(kid) %></h4></td>
          <tr></tr>
          <td><h4><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></h4</td>
        </tr>
        
      <% end %>
    
      
      
    </tbody>
  </table>
<br></br>
<%= link_to 'New Kid', new_kid_path %> <br>
<br>

👦🏽

app/views/kids/new.html.erb
<h1>New Kid</h1>

<%= render 'form', kid: @kid %>

<%= link_to 'Back', kids_path %>
<br>
<%= link_to "Log Out", "/logout" %>

app/views/kids/show.html.erb
<h1>Name: <%= @kid.name %></h1>
<h3>Saying: <%= @kid.saying %></h3>

<%= form_tag kid_path(@kid.id), method: "delete" do %>
  <%= submit_tag "Delete #{@kid.name}" %>
<% end %>


<%= link_to 'Edit', edit_kid_path(@kid) %> •
<%= link_to 'Back',kids_path %> •

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StrangerDanger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/home.html.erb
<h1> local food </h1>



<%= link_to "Log In", "/login" %>
or
Create a new account  <%= link_to "here", "/users/new" %>.
<br>
<%= link_to "Log Out", "/logout" %>

app/views/users/index.html.erb
<h1> local food </h1>

<h1><%= link_to "Catalog", "/catalog" %></h1><br>

<%= link_to "Log In", "/login" %>
or
Create a new account  <%= link_to "here", "/users/new" %>.

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="fields_with_errors">
    <h2>There were some errors:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @user do |f| %>

    <label for="Name">Name:</label><br>
    <%= f.text_field :name %> <br>
    
    <label for="Email">Email:</label><br>
      <%= f.text_field :email %> <br>
    
    <label for="Password">Password:</label><br>
    <%= f.password_field :password %> <br>
    
    <label for="Password Confirmation">Confirm Password:</label><br>
       <%= f.password_field :password_confirmation %> <br>
    <br>
    
    
    <%= f.submit  %>
  

<% end %>

app/views/users/show.html.erb
<h1> local food </h1>

<h2><%= link_to "Catalog", "/catalog" %></h2><br>

<% if @user %>
  Logged in as <%= @user.name %>
<% else %>

  <%= link_to 'Sign Up', "/signup" %>
  <%= link_to 'Log In', "/login" %>
  <% end %>

<%= link_to "Log Out", "/logout" %>